server:
  port: 8010
eureka:
  instance:
    hostname: localhost             #主机名，不配置的时候讲根据操作系统的主机名来获取
    leaseRenewalIntervalInSeconds: 15
  client:
    register-with-eureka: false     #是否要将自身的实例信息注册到Eureka服务端
    fetch-registry: false           #是否从Eureka服务端获取注册信息
    service-url:                    #eureka注册中心的地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

